### PR TITLE
Code Review: Update projects for XC8.1 (#11339)

### PR DESCRIPTION
**Pull request by samdeane**
Code review for Update projects for XC8.1 (#11339):

> It’s that time again - oh joy.

Connect to BohemianCoding/Sketch#11339.

### CODE REVIEW

**Review by opsGavin — APPROVED** [review]
I'm guessing this project doesn't use the standard xcconfig files - so 👍

**Comment by samdeane** [comment]
None of the third party ones do, no. That's something I've been meaning to mention actually, about the way you set up WebP. 

My original suggestion of combining our Xcode project with their repo was so that we might one day be able to push our project back to them as a thankyou. 

By making it dependent on BCFoundation though, and adding some actual classes that use it, you've kind of scotched that idea I suspect. 

Given that, I might have been inclined to actually go for a layout like this:

```
Modules/
   webp/        # the plain vanilla webp repo, just here for the source code 
   BCWebP/      # our XC project file, and supporting classes

```

**Comment by opsGavin** [comment]
That makes a lot of sense. I have to admit I was struggling to reconcile adding an Xcode project which we could contribute back and having the project set up so that we could use the xcconfigs. Given the choice I'd rather use the xcconfigs - not that I'm adversed to contributing, just that it gives us something more consistent to work with.

**Comment by samdeane** [comment]
Yeah. I'll make an issue to clean it up, but we should probably wait until that Jenkins submodule bug is fixed :)

**Comment by samdeane** [comment]
FYI: BohemianCoding/Sketch#11373.

**Pull request closed without merging**
