### PR TITLE
BohemianCoding/Sketch#3319 Script import: Add support for absolute and ~ paths

### PR DESCRIPTION
**Pull request by randomsequence**
I got confused with branch names, so I deleted the old one and created a named feature branch instead.

My comments still stand on the previous PR though:
https://github.com/BohemianCoding/CocoaScript/pull/1#discussion_r21744115

Ref BohemianCoding/Sketch#3319

### CODE REVIEW

**Comment by samdeane** [comment]
```
You could test the first item in pathComponents, but you'd still be testing if it's equal to @"/".
```

Ah, that's true. I think testing the first item is still slightly more legitimate, as in theory the path separator could change (yes, unlikely I know).

Slightly annoying if they pass it back though - it rather defeats the object of the exercise if we have to assume that what we'll get back is @"/"...

**Comment by samdeane** [comment]
```
NSLog(@"%i", [@"this/that.js" characterAtIndex:0] == pathSeparator);  // 0          
```

What's wrong with `[string characterAtIndex:0] == '\'); 

If we didn't use pathComponents, I'm not sure why we wouldn't want to do this. `characterAtIndex` should do the right thing with multibyte unicode characters, and in any case here we're testing something that's in the 7-bit ascii range

Am I missing something here?

**Comment by samdeane** [comment]
Review 2: looks good. Up to you whether you change the @"/" thing - not a big deal either way.

**Comment by randomsequence** [comment]
> What's wrong with `[string characterAtIndex:0] == '\');

Apparently nothing.

**Comment by randomsequence** [comment]
What we're both really looking for here is a `NSPathSeparator` constant to compare with, which sadly doesn't exist.

**Pull request merged**
